### ISSUE TITLE
SE Graal fails to build when security enabled

### ISSUE THREAD

**Issue by pfmackin** [tomas-langer/helidon-conference#10]
I enabled security per step 12 and the docker build for Graal failed 

[WARNING] Error: Unsupported features in 5 methods
[WARNING] Detailed message:
[WARNING] Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call: java.lang.invoke.MethodHandle.bindTo(Object)
[WARNING] Trace: 
[WARNING] 	at parsing java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:221)
[WARNING] Call path from entry point to java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandle, MethodType, boolean, boolean): 
[WARNING] 	at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:207)
[WARNING] 	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:194)
[WARNING] 	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:380)
[WARNING] 	at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
[WARNING] 	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
[WARNING] 	at java.lang.invoke.Invokers.checkGenericType(Invokers.java:321)
[WARNING] 	at java.lang.invoke.LambdaForm$MH/876054359.invoke_MT(LambdaForm$MH)
[WARNING] 	at io.helidon.config.objectmapping.ReflectionUtil$PropertyAccessor.setImpl(ReflectionUtil.java:427)
[WARNING] 	at io.helidon.config.objectmapping.ReflectionUtil$PropertyAccessor.lambda$set$0(ReflectionUtil.java:422)
[WARNING] 	at io.helidon.config.objectmapping.ReflectionUtil$PropertyAccessor$$Lambda$858/687888484.accept(Unknown Source)
[WARNING] 	at io.helidon.webserver.RequestRouting.fireNewWebServer(RequestRouting.java:101)
[WARNING] 	at io.helidon.webserver.WebServer$Builder.build(WebServer.java:321)
[WARNING] 	at io.helidon.webserver.WebServer.create(WebServer.java:176)
[WARNING] 	at io.helidon.examples.quickstart.se.Main.startServer(Main.java:80)
[WARNING] 	at io.helidon.examples.quickstart.se.Main.main(Main.java:56)
[WARNING] 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
[WARNING] 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
...
[WARNING] Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by tomas-langer** [comment]
Caused by usage of `config-object-mapping`. Need to investigate if this dependency can be removed (this is a Helidon issue).

**Comment by tomas-langer** [comment]
Fixed with 1.2.1
New issue found and reported in Helidon: https://github.com/oracle/helidon/issues/946
