### ISSUE TITLE
MP Tests fail after GreetHealthcheck.java added (step 7)

### ISSUE THREAD

**Issue by pfmackin** [tomas-langer/helidon-conference#6]
Once you add GreetHealthcheck.java, the build mvn package fails because it expects the greeting to be Hello.  However, the test changes the greeting to Hallo, so it fails.  The test needs to reset the greeting before doing the health check as such:

        r = client
            .target(getConnectionString("/greet/greeting"))
            .request()
            .put(Entity.entity("{\"greeting\" : \"Hello\"}", MediaType.APPLICATION_JSON));
        Assertions.assertEquals(204, r.getStatus(), "PUT status code");
        
        r = client
                .target(getConnectionString("/health"))
                .request()
                .get();
        Assertions.assertEquals(200, r.getStatus(), "GET health status code");

**Comment by tomas-langer** [comment]
The tests never work throughout the guide - I recommend skipping tests.
Other option is to fix the unit tests as you modify the code, though that would be much longer
